name: release

on:
  push:
    # 监听 main 分支的 push 事件
    branches:
      - main
# 赋予 release-please-action 权限
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  # 设置 release-please 任务
  release-please:
    # 设置任务运行环境为 ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      # 使用 release-please-action 动作来自动创建发布 PR
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: rust
          package-name: wechatv
      # 检出代码
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      
      - name: 安装 Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
        if: ${{ steps.release.outputs.release_created }}            
      - name: 构建发布版本
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
        if: ${{ steps.release.outputs.release_created }}
      - name: 创建发布包
        run: |
          mkdir -p release
          cp target/release/wechatv.exe release/
          cp README.md release/ || echo "No README.md found"
          cd release
          7z a -tzip wechatv-${{ needs.release-please.outputs.tag_name }}-windows-x64.zip *
        if: ${{ steps.release.outputs.release_created }}
          
      - name: 上传发布包到 Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/wechatv-${{ needs.release-please.outputs.tag_name }}-windows-x64.zip
          tag_name: ${{ needs.release-please.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        if: ${{ steps.release.outputs.release_created }}
